name: Melt Kernel CI

on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run build script
        run: ./build.sh ${{ inputs.release_version }}
    